# Project information
site_name: Agent Development Kit
site_url: https://adk-labs.github.io/adk-docs
site_description: >-
  Build powerful multi-agent systems with Agent Development Kit
site_dir: site

# Repository
repo_name: adk-python
repo_url: https://github.com/google/adk-python

# Copyright
copyright: Copyright Google 2025

# Custom CSS
extra_css:
  - stylesheets/custom.css

extra:
  second_repo_url: https://github.com/google/adk-java
  second_repo_name: adk-java
  second_repo_icon: fontawesome/brands/github

# Configuration
theme:
  name: material
  font:
    text: Google Sans
    code: Roboto Mono
  logo: assets/agent-development-kit.png
  favicon: assets/agent-development-kit.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true


# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        'get-started/local-testing.md': 'get-started/testing.md'
        'get-started/tutorial.md': 'tutorials/index.md'
        'guides/responsible-agents.md': 'safety/index.md'
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ko
          name: 한국어
          build: true
          nav_translations:
            Home: 홈
            Get Started: 시작하기
            Installation: 설치
            Quickstart: 빠르게 시작하기
            Quickstart (Streaming): 빠르게 시작하기 (스트리밍)
            Python: Python
            Java: Java
            Testing: 테스트하기
            Sample agents: 샘플 에이전트
            About ADK: ADK 소개

            Tutorials: 튜토리얼
            Agent Team: 에이전트 팀 구성

            Agents: 에이전트
            LLM agents: LLM 에이전트
            Workflow agents: 워크플로우 에이전트
            Sequential agents: 순차 실행 에이전트
            Loop agents: 루프 에이전트
            Parallel agents: 병렬 실행 에이전트
            Custom agents: 사용자 정의 에이전트
            Multi-agent systems: 멀티 에이전트 시스템
            Models: 모델 정의

            Tools: 도구
            Function tools: 함수형 도구
            Built-in tools: 내장 도구
            Third party tools: 서드파티 도구
            Google Cloud tools: Google Cloud 도구
            MCP tools: MCP 도구
            OpenAPI tools: OpenAPI 도구
            Authentication: 인증

            Running Agents: 에이전트 실행
            Agent Runtime: 런타임
            Runtime Config: 런타임 설정

            Deploy: 배포
            Agent Engine: 에이전트 엔진
            Cloud Run: Cloud Run
            GKE: GKE

            Sessions & Memory: 세션 및 메모리
            Session: 세션
            State: 상태
            Memory: 메모리

            Callbacks: 콜백
            Types of callbacks: 콜백의 종류
            Callback patterns: 디자인 패턴 및 모범 사례

            Artifacts: 아티팩트
            Events: 이벤트
            Context: 컨텍스트
            Evaluate: 평가
            MCP: MCP

            Bidi-streaming (live): Bidi-streaming (실시간)
            Quickstart (Bidi-streaming/live): 빠르게 시작하기 (Live)
            Streaming Tools: 스트리밍 도구
            Custom Audio Bidi-streaming app sample (SSE): 오디오 예제 (SSE)
            Custom Audio Bidi-streaming app sample (WebSockets): 오디오 예제 (WebSocket)
            Configurating Bidi-streaming behaviour: 스트리밍 설정

            Safety and Security: 보안 및 안전성
            Agent2Agent (A2A) Protocol: Agent 간 통신 (A2A 프로토콜)
            Community Resources: 커뮤니티 자료
            Contributing Guide: 기여 가이드

            API Reference: API 레퍼런스
            Python ADK: Python ADK
            Java ADK: Java ADK
        - locale: ja
          name: 日本語
          build: true
          nav_translations:
            Home: ホーム
            Get Started: はじめに
            Installation: インストール
            Quickstart: クイックスタート
            Quickstart (Streaming): クイックスタート（ストリーミング）
            Python: Python
            Java: Java
            Testing: テスト
            Sample agents: サンプルエージェント
            About ADK: ADKについて

            Tutorials: チュートリアル
            Agent Team: エージェントチーム構成

            Agents: エージェント
            LLM agents: LLMエージェント
            Workflow agents: ワークフローエージェント
            Sequential agents: シーケンシャルエージェント
            Loop agents: ループエージェント
            Parallel agents: パラレルエージェント
            Custom agents: カスタムエージェント
            Multi-agent systems: マルチエージェントシステム
            Models: モデル定義

            Tools: ツール
            Function tools: 関数ツール
            Built-in tools: 内蔵ツール
            Third party tools: サードパーティツール
            Google Cloud tools: Google Cloudツール
            MCP tools: MCPツール
            OpenAPI tools: OpenAPIツール
            Authentication: 認証

            Running Agents: エージェントの実行
            Agent Runtime: ランタイム
            Runtime Config: ランタイム設定

            Deploy: デプロイ
            Agent Engine: エージェントエンジン
            Cloud Run: Cloud Run
            GKE: GKE

            Sessions & Memory: セッションとメモリ
            Session: セッション
            State: ステート
            Memory: メモリ

            Callbacks: コールバック
            Types of callbacks: コールバックの種類
            Callback patterns: デザインパターンとベストプラクティス

            Artifacts: アーティファクト
            Events: イベント
            Context: コンテキスト
            Evaluate: 評価
            MCP: MCP

            Bidi-streaming (live): Bidiストリーミング（ライブ）
            Quickstart (Bidi-streaming/live): クイックスタート（ライブ）
            Streaming Tools: ストリーミングツール
            Custom Audio Bidi-streaming app sample (SSE): カスタムオーディオSSEサンプル
            Custom Audio Bidi-streaming app sample (WebSockets): カスタムオーディオWebSocketサンプル
            Configurating Bidi-streaming behaviour: Bidiストリーミングの設定

            Safety and Security: セキュリティと安全性
            Agent2Agent (A2A) Protocol: エージェント間プロトコル（A2A）
            Community Resources: コミュニティリソース
            Contributing Guide: コントリビューションガイド

            API Reference: APIリファレンス
            Python ADK: Python ADK
            Java ADK: Java ADK


# Navigation
nav:
  - Home: index.md
  - Get Started:
    - Get-started/index.md
    - Installation: get-started/installation.md
    - Quickstart: get-started/quickstart.md
    - Quickstart (Streaming):
      - get-started/streaming/index.md
      - Python: get-started/streaming/quickstart-streaming.md
      - Java: get-started/streaming/quickstart-streaming-java.md
    - Testing: get-started/testing.md
    - Sample agents: https://github.com/google/adk-samples
    - About ADK: get-started/about.md
  - Tutorials:
    - tutorials/index.md
    - Agent Team: tutorials/agent-team.md
  - Agents:
    - agents/index.md
    - LLM agents: agents/llm-agents.md
    - Workflow agents:
      - agents/workflow-agents/index.md
      - Sequential agents: agents/workflow-agents/sequential-agents.md
      - Loop agents: agents/workflow-agents/loop-agents.md
      - Parallel agents: agents/workflow-agents/parallel-agents.md
    - Custom agents: agents/custom-agents.md
    - Multi-agent systems: agents/multi-agents.md
    - Models: agents/models.md
  - Tools:
    - tools/index.md
    - Function tools: tools/function-tools.md
    - Built-in tools: tools/built-in-tools.md
    - Third party tools: tools/third-party-tools.md
    - Google Cloud tools: tools/google-cloud-tools.md
    - MCP tools: tools/mcp-tools.md
    - OpenAPI tools: tools/openapi-tools.md
    - Authentication: tools/authentication.md
  - Running Agents:
    - Agent Runtime: runtime/index.md
    - Runtime Config: runtime/runconfig.md
  - Deploy:
    - deploy/index.md
    - Agent Engine: deploy/agent-engine.md
    - Cloud Run: deploy/cloud-run.md
    - GKE: deploy/gke.md
  - Sessions & Memory:
    - sessions/index.md
    - Session: sessions/session.md
    - State: sessions/state.md
    - Memory: sessions/memory.md
  - Callbacks:
    - callbacks/index.md
    - Types of callbacks: callbacks/types-of-callbacks.md
    - Callback patterns: callbacks/design-patterns-and-best-practices.md
  - Artifacts:
    - artifacts/index.md
  - Events:
    - events/index.md
  - Context:
    - context/index.md
  - Evaluate:
    - evaluate/index.md
  - MCP:
    - mcp/index.md
  - Bidi-streaming (live):
    - streaming/index.md
    - Quickstart (Bidi-streaming/live): get-started/streaming/index.md
    - Streaming Tools: streaming/streaming-tools.md
    - Custom Audio Bidi-streaming app sample (SSE): streaming/custom-streaming.md
    - Custom Audio Bidi-streaming app sample (WebSockets): streaming/custom-streaming-ws.md
    - Configurating Bidi-streaming behaviour: streaming/configuration.md
  - Safety and Security: safety/index.md
  - Agent2Agent (A2A) Protocol: https://github.com/google/A2A/
  - Community Resources: community.md
  - Contributing Guide: contributing-guide.md
  - API Reference:
    - api-reference/index.md
    - Python ADK: api-reference/python/index.html
    - Java ADK: api-reference/java/index.html
